@echo off
setlocal

set "SCRIPT_DIR=%~dp0"
set "REPO_ROOT=%SCRIPT_DIR%.."

call :require_bun
if errorlevel 1 exit /b 1

if "%~1"=="" goto :menu
if /I "%~1"=="menu" goto :menu

if /I "%~1"=="dev" call :run_build dev & goto :end
if /I "%~1"=="canary" call :run_build canary & goto :end
if /I "%~1"=="stable" call :run_build stable & goto :end

echo Usage: %~nx0 [dev^|canary^|stable^|menu]
exit /b 1

:menu
cls
echo =========================================
echo    Your Little Oyachi 2 Build Console
echo =========================================
echo 1^) Build DEV
echo 2^) Build CANARY
echo 3^) Build STABLE
echo 4^) Build ALL ^(dev/canary/stable^)
echo 5^) Open build folder
echo 6^) Show format support
echo 7^) Exit
echo.
set "CHOICE="
set /p CHOICE=Select an option [1-7]: 

if "%CHOICE%"=="1" call :run_build dev & goto :wait_and_menu
if "%CHOICE%"=="2" call :run_build canary & goto :wait_and_menu
if "%CHOICE%"=="3" call :run_build stable & goto :wait_and_menu
if "%CHOICE%"=="4" call :run_build dev & call :run_build canary & call :run_build stable & goto :wait_and_menu
if "%CHOICE%"=="5" call :open_build_folder & goto :wait_and_menu
if "%CHOICE%"=="6" call :print_formats & goto :wait_and_menu
if "%CHOICE%"=="7" goto :end

echo Invalid option: %CHOICE%
goto :wait_and_menu

:wait_and_menu
echo.
pause
goto :menu

:require_bun
where bun >nul 2>&1
if errorlevel 1 (
  echo bun is required but was not found. Install Bun from https://bun.sh
  exit /b 1
)
exit /b 0

:run_build
set "BUILD_ENV=%~1"
cd /d "%REPO_ROOT%"

echo.
echo Building Electrobun app on this host OS only...
echo For all OS builds ^(macOS, Windows, Linux^), use .github/workflows/electrobun-builds.yml
echo.

bun install
if errorlevel 1 exit /b 1

bun run build -- --env=%BUILD_ENV%
if errorlevel 1 exit /b 1

echo.
echo Build complete. Output root: %REPO_ROOT%\build
call :print_formats
exit /b 0

:open_build_folder
start "" "%REPO_ROOT%\build"
exit /b 0

:print_formats
echo.
echo Format support in Electrobun today:
echo - Windows: .exe ^(supported^), .msi ^(not generated by Electrobun^)
echo - macOS: .app and .dmg ^(supported^)
echo - Linux: tar.gz installer/bundle ^(supported^), .AppImage/.deb/.rpm ^(not generated by Electrobun^)
exit /b 0

:end
endlocal
