#!/usr/bin/env bash
set -euo pipefail

BUILD_ENV="${1:-stable}"
OPEN_AFTER_BUILD="${2:-}"

case "${BUILD_ENV}" in
  dev|canary|stable) ;;
  *)
    echo "Usage: $0 [dev|canary|stable] [open]"
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

if ! command -v bun >/dev/null 2>&1; then
  echo "bun is required but not found. Install Bun from https://bun.sh"
  exit 1
fi

echo "Building Electrobun app on this host OS only..."
echo "For all OS builds (macOS, Windows, Linux), use .github/workflows/electrobun-builds.yml"

cd "${REPO_ROOT}"
bun install
bun run build -- --env="${BUILD_ENV}"

echo
echo "Build complete. Output root: ${REPO_ROOT}/build"
echo
echo "Format support in Electrobun today:"
echo "- Windows: .exe (supported), .msi (not generated by Electrobun)"
echo "- macOS: .app and .dmg (supported)"
echo "- Linux: tar.gz installer/bundle (supported), .AppImage/.deb/.rpm (not generated by Electrobun)"

if [[ "${OPEN_AFTER_BUILD}" == "open" ]]; then
  if command -v open >/dev/null 2>&1; then
    open "${REPO_ROOT}/build"
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "${REPO_ROOT}/build" >/dev/null 2>&1 || true
  fi
fi
