#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

require_bun() {
  if ! command -v bun >/dev/null 2>&1; then
    echo "bun is required but not found. Install Bun from https://bun.sh"
    exit 1
  fi
}

open_build_folder() {
  if command -v open >/dev/null 2>&1; then
    open "${REPO_ROOT}/build"
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "${REPO_ROOT}/build" >/dev/null 2>&1 || true
  fi
}

print_formats() {
  echo
  echo "Format support in Electrobun today:"
  echo "- Windows: .exe (supported), .msi (not generated by Electrobun)"
  echo "- macOS: .app and .dmg (supported)"
  echo "- Linux: tar.gz installer/bundle (supported), .AppImage/.deb/.rpm (not generated by Electrobun)"
}

run_build() {
  local build_env="$1"

  echo
  echo "Building Electrobun app on this host OS only..."
  echo "For all OS builds (macOS, Windows, Linux), use .github/workflows/electrobun-builds.yml"

  cd "${REPO_ROOT}"
  bun install
  bun run build -- --env="${build_env}"

  echo
  echo "Build complete. Output root: ${REPO_ROOT}/build"
  print_formats
}

run_all_builds() {
  run_build dev
  run_build canary
  run_build stable
}

pause_prompt() {
  printf "\nPress Enter to continue..."
  read -r _
}

show_menu() {
  while true; do
    clear || true
    cat <<'EOF'
=========================================
   Your Little Oyachi 2 Build Console
=========================================
1) Build DEV
2) Build CANARY
3) Build STABLE
4) Build ALL (dev/canary/stable)
5) Open build folder
6) Show format support
7) Exit
EOF

    printf "Select an option [1-7]: "
    read -r choice

    case "${choice}" in
      1) run_build dev; pause_prompt ;;
      2) run_build canary; pause_prompt ;;
      3) run_build stable; pause_prompt ;;
      4) run_all_builds; pause_prompt ;;
      5) open_build_folder; pause_prompt ;;
      6) print_formats; pause_prompt ;;
      7) exit 0 ;;
      *) echo "Invalid option: ${choice}"; pause_prompt ;;
    esac
  done
}

require_bun

if [[ "${1:-}" == "" || "${1:-}" == "menu" ]]; then
  show_menu
  exit 0
fi

case "${1}" in
  dev|canary|stable)
    run_build "${1}"
    if [[ "${2:-}" == "open" ]]; then
      open_build_folder
    fi
    ;;
  *)
    echo "Usage: $0 [dev|canary|stable|menu] [open]"
    exit 1
    ;;
esac
