@echo off
setlocal

set "BUILD_ENV=%~1"
if "%BUILD_ENV%"=="" set "BUILD_ENV=stable"

if /I not "%BUILD_ENV%"=="dev" if /I not "%BUILD_ENV%"=="canary" if /I not "%BUILD_ENV%"=="stable" (
  echo Usage: %~nx0 [dev^|canary^|stable]
  exit /b 1
)

set "SCRIPT_DIR=%~dp0"
set "REPO_ROOT=%SCRIPT_DIR%.."
cd /d "%REPO_ROOT%"

where bun >nul 2>&1
if errorlevel 1 (
  echo bun is required but was not found. Install Bun from https://bun.sh
  exit /b 1
)

echo Building Electrobun app on this host OS only...
echo For all OS builds ^(macOS, Windows, Linux^), use .github/workflows/electrobun-builds.yml

bun install
if errorlevel 1 exit /b 1

bun run build -- --env=%BUILD_ENV%
if errorlevel 1 exit /b 1

echo.
echo Build complete. Output root: %REPO_ROOT%\build
echo.
echo Format support in Electrobun today:
echo - Windows: .exe ^(supported^), .msi ^(not generated by Electrobun^)
echo - macOS: .app and .dmg ^(supported^)
echo - Linux: tar.gz installer/bundle ^(supported^), .AppImage/.deb/.rpm ^(not generated by Electrobun^)

start "" "%REPO_ROOT%\build"

endlocal
